#define RES_IMAGE 1
#define RES_FONT_BLUE 2
#define RES_FONT_BLACK 3
#define RES_SELECTED_EDITBOX 4
#define RES_UNSELECTED_EDITBOX 5
#define RES_UNSELECTED_BUTTON 6
#define RES_TEXT_BOX 7
#define RES_BACKGROUND 8
#define RES_SELECTED_LIST 9
#define RES_UNSELECTED_LIST 10
#define RES_SELECTED_ALBUM 11
#define RES_UNSELECTED_ALBUM 12
#define RESP_DATA 13
#define RESP_IMAGE 14
#define RES_TEMPTHUMB 15
#define RES_TEMP 16
#define RES_LOADINGTHUMB 17
#define RES_LOADING 18
#define RES_MISSINGTHUMB 19
#define RES_CHANGE_STAR 20
#define RES_LOADING_FLIP 21
#define RES_EMPTY_FLIP 22
#define RES_BOX_SELECTED 23
#define RES_BOX_UNSELECTED 24
#define URL "http://dev.mytcg.net/_phone/"
#define URLSIZE 28


