#ifndef CONFIG_H
#define CONFIG_H
#define MA_PROF_SUPPORT_JAVAPACKAGE_BLUETOOTH
#define MA_PROF_SUPPORT_JAVAPACKAGE_WMAPI
#define MA_PROF_SUPPORT_JAVAPACKAGE_FILECONNECTION
#define MA_PROF_SUPPORT_JAVAPACKAGE_PIMAPI
#define MA_PROF_SUPPORT_JAVAPACKAGE_MMAPI
#define PHONE_RELEASE
#define MOSYNC_COMMERCIAL
#endif /* CONFIG_H */
