#define RES_IMAGE 1
#define RES_SELECTED_EDITBOX 2
#define RES_UNSELECTED_EDITBOX 3
#define RES_UNSELECTED_BUTTON 4
#define RES_SELECTED_BUTTON 5
#define RES_TEXT_BOX 6
#define RES_BACKGROUND 7
#define RES_SELECTED_LIST 8
#define RES_UNSELECTED_LIST 9
#define RES_SELECTED_ALBUM 10
#define RES_UNSELECTED_ALBUM 11
#define RESP_DATA 12
#define RESP_IMAGE 13
#define RES_TEMPTHUMB 14
#define RES_TEMP 15
#define RES_LOADINGTHUMB 16
#define RES_MISSINGTHUMB 17
#define RES_CHANGE_STAR 18
#define RES_EMPTY_FLIP 19
#define RES_BOX_SELECTED 20
#define RES_BOX_UNSELECTED 21
#define RES_LOADING1 22
#define RES_LOADING2 23
#define RES_LOADING3 24
#define RES_LOADING4 25
#define RES_LOADING5 26
#define RES_LOADING6 27
#define RES_LOADING7 28
#define RES_LOADING8 29
#define RES_LOADING9 30
#define RES_LOADING10 31
#define RES_LOADING11 32
#define RES_LOADING12 33
#define RES_LOADING13 34
#define RES_LOADING14 35
#define RES_LOADING15 36
#define RES_LOADING16 37
#define RES_LOADING17 38
#define RES_LOADING18 39
#define RES_LOADING_FLIP1 40
#define RES_LOADING_FLIP2 41
#define RES_LOADING_FLIP3 42
#define RES_LOADING_FLIP4 43
#define RES_LOADING_FLIP5 44
#define RES_LOADING_FLIP6 45
#define RES_LOADING_FLIP7 46
#define RES_LOADING_FLIP8 47
#define RES_LOADING_FLIP9 48
#define RES_LOADING_FLIP10 49
#define RES_LOADING_FLIP11 50
#define RES_LOADING_FLIP12 51
#define RES_LOADING_FLIP13 52
#define RES_LOADING_FLIP14 53
#define RES_LOADING_FLIP15 54
#define RES_LOADING_FLIP16 55
#define RES_LOADING_FLIP17 56
#define RES_LOADING_FLIP18 57
#define RES_LEFT_ARROW 58
#define RES_RIGHT_ARROW 59
#define RES_ALBUM 60
#define RES_ALBUM_THUMB 61
#define RES_AUCTIONS 62
#define RES_AUCTIONS_THUMB 63
#define RES_CREDITS 64
#define RES_CREDITS_THUMB 65
#define RES_LOGOUT 66
#define RES_LOGOUT_THUMB 67
#define RES_NOTIFICATIONS 68
#define RES_NOTIFICATIONS_THUMB 69
#define RES_PROFILE 70
#define RES_PROFILE_THUMB 71
#define RES_SHOP 72
#define RES_SHOP_THUMB 73

#define RES_DESELECTED_LIST_DOT 74
#define RES_SELECTED_LIST_DOT 75

#define RES_ICONS_BACK 76
#define RES_SELECT_ICON 77
#define RES_UNSELECT_ICON 78

#define RES_HEAD 79

#define RES_BLANK 80

/* Custom Variables per App */

#define RES_FONT_BLACK 81
#define RES_FONT_GREEN 82
#define RES_FONT_GREY 83
#define RES_FONT_WHITE 84

#define RES_DROPDOWNITEM_SEL 85
#define RES_DROPDOWNITEM_UNSEL 86
#define RES_DROPDOWNBOX_SEL 87
#define RES_DROPDOWNBOX_UNSEL 88
#define RES_POPUP_HEADER 89

#define RES_BIG_LEFT_ARROW 90
#define RES_BIG_RIGHT_ARROW 91

#define THUMB_HEIGHT 74
#define ITEM_HEIGHT 48

#define URL "http://sarugbycards.com/_phone/"
#define URLSIZE 31

//we also need to define the x and y coordinates at which to split the images up
#define EDITBOX_X_LEFT 20
#define EDITBOX_X_RIGHT 28
#define EDITBOX_Y_TOP 22
#define EDITBOX_Y_BOTTOM 26

#define BUTTON_X_LEFT 18
#define BUTTON_X_RIGHT 82
#define BUTTON_Y_TOP 18
#define BUTTON_Y_BOTTOM 82

#define BACKGROUND_X_LEFT 1
#define BACKGROUND_X_RIGHT 464
#define BACKGROUND_Y_TOP 1
#define BACKGROUND_Y_BOTTOM 399

#define HEAD_X_LEFT 130
#define HEAD_X_RIGHT 138
#define HEAD_Y_TOP 43
#define HEAD_Y_BOTTOM 44

#define LIST_X_LEFT 22
#define LIST_X_RIGHT 168
#define LIST_Y_TOP 16
#define LIST_Y_BOTTOM 32

#define LISTNOARROWS_X_LEFT 16
#define LISTNOARROWS_X_RIGHT 77
#define LISTNOARROWS_Y_TOP 16
#define LISTNOARROWS_Y_BOTTOM 32

#define ALBUM_X_LEFT 4
#define ALBUM_X_RIGHT 168
#define ALBUM_Y_TOP 57
#define ALBUM_Y_BOTTOM 68

#define TEXT_X_LEFT 16
#define TEXT_X_RIGHT 32
#define TEXT_Y_TOP 16
#define TEXT_Y_BOTTOM 32

#define DROPDOWNITEM_X_LEFT 5
#define DROPDOWNITEM_X_RIGHT 33
#define DROPDOWNITEM_Y_TOP 19
#define DROPDOWNITEM_Y_BOTTOM 20

#define DROPDOWNBOX_X_LEFT 140
#define DROPDOWNBOX_X_RIGHT 150
#define DROPDOWNBOX_Y_TOP 35
#define DROPDOWNBOX_Y_BOTTOM 37

#define DROPDOWNBACK_X_LEFT 10
#define DROPDOWNBACK_X_RIGHT 40
#define DROPDOWNBACK_Y_TOP 10
#define DROPDOWNBACK_Y_BOTTOM 40

#define POPUP_HEADER_X_LEFT 10
#define POPUP_HEADER_X_RIGHT 48
#define POPUP_HEADER_Y_TOP 24
#define POPUP_HEADER_Y_BOTTOM 25

//the default heights and widths for various widgets
#define DEFAULT_LABEL_HEIGHT 48
#define ALBUM_ITEM_HEIGHT 74
#define THUMBNAIL_HEIGHT 64
#define MIN_SOFTKEY_BAR_HEIGHT 42
#define DEFAULT_SMALL_LABEL_HEIGHT 24
#define DEFAULT_DETAIL_HEADER_HEIGHT 36
#define DEFAULT_DETAILS_ITEM_HEIGHT 80
#define PADDING 5
#define ICON_HEIGHT 69
#define DOT_HEIGHT 16
#define ARROW_WIDTH 35
#define BIG_ARROW_WIDTH 31
#define MIN_MENU_ICON_WIDTH 64

#define DEFAULT_DROPDOWN_HEIGHT 38
#define DEFAULT_DROPDOWNITEM_HEIGHT 30

//renumber the menu options if one is removed
//numbers must always run sequential for index
#define OP_ALBUMS 0
#define OP_SHOP 1
#define OP_AUCTIONS 2
#define OP_NOTIFICATIONS 3
#define OP_CREDITS 4
#define OP_PROFILE 5
#define OP_LOGOUT 6

#include <MAUtil/String.h>

using namespace MAUtil;

#ifndef _MAHeaders_H_
#define _MAHeaders_H_

static String FILE_PREFIX = "saru_";

#endif
